apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sample-app
  template:
    metadata:
      labels:
        app: java-sample-app
    spec:
      containers:
      - name: java-sample-app
        image: saitejatamiri/java-sample-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-sample-app
spec:
  type: NodePort
  selector:
    app: java-sample-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    # Removed nodePort to let Kubernetes choose a free one
